import io
import csv
from datetime import datetime
from xml.sax.saxutils import escape as _xml_escape
import pandas as pd
from typing import Literal

from fastapi import Response
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer

def _format_currency(val) -> str:
    if val is None or pd.isna(val):
        return ""
    try:
        return f"{float(val):,.2f}"
    except (ValueError, TypeError):
        return str(val)

# A cell that begins with one of these is treated as a formula by Excel / Sheets /
# LibreOffice. Prefixing with a single quote forces text interpretation, which
# defeats CSV / formula injection (e.g. a customer name of =HYPERLINK(...) or
# =cmd|'/c ...'!A1). Only relevant for spreadsheet outputs, not PDF.
_FORMULA_PREFIXES = ("=", "+", "-", "@", "\t", "\r")


def _neutralize_formula(value):
    if isinstance(value, str) and value and value[0] in _FORMULA_PREFIXES:
        return "'" + value
    return value


def _sanitize_data(data: list[dict], neutralize_formulas: bool = False) -> list[dict]:
    """Sanitize data for export, flattening complex objects if needed.

    When ``neutralize_formulas`` is set (CSV / Excel outputs), string cells that
    could be interpreted as spreadsheet formulas are escaped to plain text.
    """
    sanitized = []
    for row in data:
        new_row = {}
        for key, value in row.items():
            if isinstance(value, datetime):
                new_row[key] = value.strftime("%Y-%m-%d %H:%M:%S")
            elif value is None:
                new_row[key] = ""
            elif neutralize_formulas:
                new_row[key] = _neutralize_formula(value)
            else:
                new_row[key] = value
        sanitized.append(new_row)
    return sanitized

def export_csv(data: list[dict]) -> bytes:
    """Generate CSV bytes from a list of dicts."""
    if not data:
        return b""
    data = _sanitize_data(data, neutralize_formulas=True)

    output = io.StringIO()
    writer = csv.DictWriter(output, fieldnames=data[0].keys())
    writer.writeheader()
    writer.writerows(data)
    return output.getvalue().encode('utf-8')

def export_excel(data: list[dict], title: str = "Export") -> bytes:
    """Generate Excel bytes from a list of dicts, with basic formatting."""
    if not data:
        # Create empty excel file
        df = pd.DataFrame()
    else:
        data = _sanitize_data(data, neutralize_formulas=True)
        df = pd.DataFrame(data)

    output = io.BytesIO()
    with pd.ExcelWriter(output, engine='openpyxl') as writer:
        df.to_excel(writer, index=False, sheet_name=title[:31])
        
        # Optional: Auto-adjust column widths
        worksheet = writer.sheets[title[:31]]
        for idx, col in enumerate(df.columns):
            max_len = max(
                df[col].astype(str).map(len).max() if not df.empty else 0,
                len(str(col))
            ) + 2
            worksheet.column_dimensions[worksheet.cell(row=1, column=idx+1).column_letter].width = min(max_len, 50)
            
    return output.getvalue()

def export_pdf(data: list[dict], title: str, user_name: str) -> bytes:
    """Generate a landscape PDF report from a list of dicts."""
    buffer = io.BytesIO()
    # Use landscape A4 to fit more columns
    doc = SimpleDocTemplate(
        buffer,
        pagesize=landscape(A4),
        rightMargin=30,
        leftMargin=30,
        topMargin=30,
        bottomMargin=30,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "ReportTitle",
        parent=styles["Heading1"],
        fontSize=16,
        spaceAfter=10,
        alignment=1 # Center
    )
    meta_style = ParagraphStyle(
        "ReportMeta",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.dimgrey,
        spaceAfter=20,
        alignment=1 # Center
    )

    elements = []

    # Header Information. user_name (and title, defensively) are XML-escaped since
    # they are rendered as reportlab Paragraph markup; user_name derives from a
    # user-controlled full_name. Table cells below are plain strings (not parsed).
    elements.append(Paragraph(_xml_escape(str(title)), title_style))
    meta_text = f"Generated by: {_xml_escape(str(user_name))} | Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    elements.append(Paragraph(meta_text, meta_style))
    elements.append(Spacer(1, 10))

    if not data:
        elements.append(Paragraph("No data available for the selected filters.", styles["Normal"]))
        doc.build(elements)
        buffer.seek(0)
        return buffer.read()

    data = _sanitize_data(data)
    
    headers = list(data[0].keys())
    display_headers = [h.replace('_', ' ').title() for h in headers]
    
    table_data = [display_headers]
    for row in data:
        table_row = []
        for key in headers:
            val = row[key]
            str_val = str(val) if val != "" else ""
            if len(str_val) > 100:
                str_val = str_val[:97] + "..."
            if ('amount' in key.lower() or 'balance' in key.lower() or 'price' in key.lower() or 'total' in key.lower()) and isinstance(val, (int, float)):
                 str_val = _format_currency(val)
            table_row.append(str_val)
        table_data.append(table_row)

    available_width = 782
    col_widths = []
    
    avg_len_per_col = []
    for col_idx in range(len(headers)):
        lengths = [len(str(table_data[r][col_idx])) for r in range(len(table_data))]
        avg_len = sum(min(l, 40) for l in lengths) / len(lengths)
        avg_len = max(avg_len, len(display_headers[col_idx]), 5)
        avg_len_per_col.append(avg_len)
        
    total_len = sum(avg_len_per_col)
    for avg_len in avg_len_per_col:
        width = (avg_len / total_len) * available_width
        col_widths.append(width)

    t = Table(table_data, colWidths=col_widths, repeatRows=1)
    
    ts = TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#f3f4f6")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
        ('ALIGN', (0, 0), (-1, 0), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 10),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
        ('TOPPADDING', (0, 0), (-1, 0), 8),
        ('BACKGROUND', (0, 1), (-1, -1), colors.white),
        ('TEXTCOLOR', (0, 1), (-1, -1), colors.black),
        ('ALIGN', (0, 1), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 1), (-1, -1), 8),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#f9fafb")]),
    ])
    
    for i, header in enumerate(headers):
        if 'amount' in header.lower() or 'balance' in header.lower() or 'price' in header.lower() or 'total' in header.lower() or 'quantity' in header.lower() or 'rate' in header.lower():
            ts.add('ALIGN', (i, 1), (i, -1), 'RIGHT')
            
    t.setStyle(ts)
    elements.append(t)

    def add_page_number(canvas, doc):
        page_num = canvas.getPageNumber()
        text = f"Page {page_num}"
        canvas.setFont('Helvetica', 9)
        canvas.setFillColor(colors.dimgrey)
        canvas.drawRightString(800, 20, text)
        canvas.drawString(40, 20, "Sri Naga Sai ERP")

    doc.build(elements, onFirstPage=add_page_number, onLaterPages=add_page_number)
    buffer.seek(0)
    return buffer.read()

def generate_export_response(data: list[dict], format: Literal["csv", "xlsx", "pdf"], title: str, user_name: str) -> Response:
    """Generate a FastAPI Response with appropriate headers based on the format."""
    filename = f"{title.lower().replace(' ', '_')}_{datetime.now().strftime('%Y%m%d')}.{format}"
    
    if format == "csv":
        content = export_csv(data)
        media_type = "text/csv"
    elif format == "xlsx":
        content = export_excel(data, title)
        media_type = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    elif format == "pdf":
        content = export_pdf(data, title, user_name)
        media_type = "application/pdf"
    else:
        raise ValueError("Unsupported format")

    return Response(
        content=content,
        media_type=media_type,
        headers={"Content-Disposition": f"attachment; filename={filename}"}
    )
