"""activity log fields

Revision ID: 6cb8ab51dc57
Revises: de2a4eec7a3f
Create Date: 2026-07-02 14:40:12.852642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cb8ab51dc57'
down_revision: Union[str, Sequence[str], None] = 'de2a4eec7a3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('module', sa.String(length=100), nullable=True))
    op.add_column('activity_logs', sa.Column('object_affected', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_logs', 'object_affected')
    op.drop_column('activity_logs', 'module')
    # ### end Alembic commands ###
