"""Add display_name to documents

Revision ID: c604e523626c
Revises: 6cb8ab51dc57
Create Date: 2026-07-05 18:23:18.319108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c604e523626c'
down_revision: Union[str, Sequence[str], None] = '6cb8ab51dc57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('display_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'display_name')
    # ### end Alembic commands ###
