"""add ocr fields

Revision ID: de2a4eec7a3f
Revises: 288278970a5e
Create Date: 2026-06-30 10:05:43.995324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de2a4eec7a3f'
down_revision: Union[str, Sequence[str], None] = '288278970a5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_metadata', sa.Column('invoice_number', sa.String(length=100), nullable=True))
    op.add_column('document_metadata', sa.Column('customer_details', sa.Text(), nullable=True))
    op.add_column('document_metadata', sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('document_metadata', sa.Column('gst_number', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_metadata', 'gst_number')
    op.drop_column('document_metadata', 'amount')
    op.drop_column('document_metadata', 'customer_details')
    op.drop_column('document_metadata', 'invoice_number')
    # ### end Alembic commands ###
