"""Phase 3

Revision ID: eb28dc9bf27b
Revises: 9f77953595e4
Create Date: 2026-06-24 18:24:43.902825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb28dc9bf27b'
down_revision: Union[str, Sequence[str], None] = '9f77953595e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('ht_sc_number', sa.String(length=50), nullable=True))
    op.add_column('loans', sa.Column('payment_frequency', sa.String(length=20), nullable=False, comment='e.g. monthly, quarterly'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'payment_frequency')
    op.drop_column('customers', 'ht_sc_number')
    # ### end Alembic commands ###
